version: '3.8'
services:

## Book Manager/Requester
  readarr:
    image: lscr.io/linuxserver/readarr
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${READARR_CFG}:/config
      - ${BOOK_DIR}:/books #optional
      - ${DOWNLOAD_DIR}:/downloads #optional
    ports:
      - ${READARR_PORT}:8787
    restart: unless-stopped

## Download Client
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DELUGE_CFG}:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - ${DELUGE_PORT}:8112
      - 6881:6881
      - 6881:6881/udp

## Bookstack (Client Reader)
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=<yourdbpass>
      - DB_DATABASE=bookstackapp
    volumes:
      - ${BOOKSTACK_CFG}:/config
    ports:
      - ${BOOKSTACK_PORT}:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - ${BOOKSTACK_DB_CFG}:/config
    restart: unless-stopped