version: '3.8'
services:

## Book Manager/Requester
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${READARR_CFG}:/config
      - ${BOOK_DIR}:/books #optional
      - ${DOWNLOAD_DIR}:/downloads #optional
    ports:
      - ${READARR_PORT}:8787
    restart: unless-stopped

## Download Client
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DELUGE_CFG}:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - ${DELUGE_PORT}:8112
      - 6881:6881
      - 6881:6881/udp

## Calibre (Book Database)
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ${CALIBRE_CFG}:/config
    ports:
      - ${CALIBRE_PORT1}:8080
      - ${CALIBRE_PORT2}:8081
    restart: unless-stopped

## Calibre Web (Online Reader)

  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${CALIBRE_CFG}:/config
      - ${BOOK_DIR}:/books
    ports:
      - ${CALIBRE_WEB_PORT}:8083
    restart: unless-stopped